version: "3.8"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins-with-docker
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    user: root
    privileged: true
    environment:
      DOCKER_HOST: tcp://dind:2375
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - dind
    restart: unless-stopped

  dind:
    image: docker:dind
    container_name: dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - dind_storage:/var/lib/docker
    restart: unless-stopped

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: sonardb
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token YOUR_CLOUDFLARED_TOKEN_HERE

volumes:
  jenkins_home:
  sonar_db_data:
  dind_storage:
